apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: howmuch.duckdns.org
  namespace: howmuch
spec:
  secretName: howmuch.duckdns.org
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - howmuch.duckdns.org

