name: publish
on: workflow_dispatch

permissions:
  packages: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          module: cicd
          workdir: cicd
          args: build-and-publish --src=..:howmuchview --registry_username=${{ github.repository_owner }} --registry_password=env:GH_TOKEN --secret_key=env:SECRET_KEY --ynab_access_token=env:YNAB_ACCESS_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
