name: publish
on: workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: .env file
        run: |
          echo "SECRET_KEY=$SECRET_KEY" >> .env
          echo "YNAB_ACCESS_TOKEN=$YNAB_ACCESS_TOKEN" >> .env
          echo "BUDGET_ID=$BUDGET_ID" >> .env
          echo "CATEGORY_ID=$CATEGORY_ID" >> .env
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
          BUDGET_ID: ${{ secrets.BUDGET_ID }}
          CATEGORY_ID: ${{ secrets.CATEGORY_ID }}

      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          module: cicd
          workdir: cicd
          args: build-and-publish --src=..:howmuchview --registry_username=${{ github.repository_owner }} --registry_password=env:GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
