name: publish
run-name: version ${{ github.run_number }}

on: workflow_dispatch

permissions:
  packages: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/delete-package-versions@v5
        with: 
          package-name: 'howmuch'
          package-type: 'container'
          min-versions-to-keep: 3
          ignore-versions: '^local$'

      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          module: cicd
          workdir: cicd
          args: build-and-publish --src=..:howmuchview --registry_username=${{ github.repository_owner }} --registry_password=env:GH_TOKEN --secret_key=env:SECRET_KEY --jo_hashed_password=env:JO_HASHED_PASSWORD --ynab_access_token=env:YNAB_ACCESS_TOKEN --image_tag=${{ github.run_number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
          JO_HASHED_PASSWORD: ${{ secrets.JO_HASHED_PASSWORD }}
