name: test
on: workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          module: cicd
          workdir: cicd
          args: test --src=..:howmuchview
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          YNAB_ACCESS_TOKEN: ${{ secrets.YNAB_ACCESS_TOKEN }}
          BUDGET_ID: ${{ secrets.BUDGET_ID }}
          CATEGORY_ID: ${{ secrets.CATEGORY_ID }}
